### ISSUE TITLE
albumentations

### ISSUE THREAD

**Issue by leonard-cooper** [4uiiurz1/pytorch-nested-unet#51]
Hello, may I ask which version of albumentations did you use in your code? Now some features of this library have changed, so I do not know which version to use. Thank you very much!

**Comment by marrylin2019** [comment]
Have you got a correct version, or any way to solve? I meet this error either. 
Error prompt looks like:
`Traceback (most recent call last):
  File "PATH\pytorch-nested-unet\train.py", line 354, in <module>
    main()
  File "PATH\pytorch-nested-unet\train.py", line 253, in main
    transforms.RandomRotate90(),
AttributeError: module 'albumentations.augmentations.transforms' has no attribute 'RandomRotate90'`

**Comment by marrylin2019** [comment]
Ok, I find the correct version via try each released version in the  albumentations' git repository😂.
Use `pip install albumentations==0.5.2` under `conda` environment or `pip3 install albumentations==0.5.2` via pure pip.

**Comment by mornedev** [comment]
I can confirm, version 0.5.2 works for me. Thanks @marrylin2019 !

**Comment by figcommon** [comment]
I solved the same problem by this way, may be it seems so rude.hhhh
```
import albumentations as A ,
# transforms.RandomRotate90(),
A.RandomRotate90(),
# transforms.Flip(),
A.Flip(),
```
